"""empty message

Revision ID: 37d103108f2c
Revises: c03cb6dd81f7
Create Date: 2022-03-14 23:49:17.479581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d103108f2c'
down_revision = 'c03cb6dd81f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruitment', sa.Column('user_id', sa.Integer(), nullable=True, comment='拥有者id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruitment', 'user_id')
    # ### end Alembic commands ###
