"""empty message

Revision ID: ec50923574e4
Revises: 37d103108f2c
Create Date: 2022-03-15 22:19:26.780441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec50923574e4'
down_revision = '37d103108f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='简历信息ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='拥有者id'),
    sa.Column('info', sa.String(length=20), nullable=True, comment='信息'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
